version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 on your machine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: always
