packages:
  - "apps/*"
  - "packages/*"
shared-workspace-lockfile: true

catalog:
  lucide-react: ^0.475.0
  tailwindcss: ^3.4.1
  postcss: ^8
  eslint: ^9.20.0
  typescript: ^5.6.3
  "@types/node": ^20
  sonner: ^1.7.4
  zod: ^3.24.1
  date-fns: ^4.1.0
  drizzle-orm: ^0.39.3
  "@libsql/client": ^0.14.0
  "@faker-js/faker": ^9.5.0
  "@t3-oss/env-nextjs": ^0.12.0
  resend: ^4.1.2

catalogs:
  react:
    next: 15.2.1
    react: ^19.0.0
    react-dom: ^19.0.0
    "@types/react": ^19
    "@types/react-dom": ^19
